import React, { useState, useEffect } from "react";
import {
  Table,
  Mail,
  ExternalLink,
  Plus,
  RefreshCw,
  Send,
  CheckCircle2,
  AlertCircle,
  FileSpreadsheet,
  Clock,
  User,
  LogOut,
} from "lucide-react";
import { GoogleSignInButton } from "./GoogleSignInButton.tsx";
import { ConfirmModal } from "./ConfirmModal.tsx";
import {
  initAuth,
  googleSignIn,
  logout,
  getAccessToken,
} from "../services/workspaceAuth.ts";
import {
  findOrCreateSpreadsheet,
  appendRehearsalRow,
  fetchRehearsalRows,
  sendRehearsalEmail,
  fetchSentRehearsalEmails,
  RehearsalRecord,
  SentEmailRecord,
} from "../services/googleWorkspace.ts";

export const WorkspaceHub: React.FC = () => {
  const [currentUser, setCurrentUser] = useState<any | null>(null);
  const [isAuthLoading, setIsAuthLoading] = useState(false);
  const [sheetUrl, setSheetUrl] = useState<string | null>(null);
  const [sheetId, setSheetId] = useState<string | null>(null);
  const [sheetRows, setSheetRows] = useState<string[][]>([]);
  const [sentEmails, setSentEmails] = useState<SentEmailRecord[]>([]);
  const [isLoadingData, setIsLoadingData] = useState(false);

  // Modals
  const [addSheetModalOpen, setAddSheetModalOpen] = useState(false);
  const [sendMailModalOpen, setSendMailModalOpen] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);

  // Form states
  const [newTitle, setNewTitle] = useState("Executive Keynote Practice");
  const [newWpm, setNewWpm] = useState(145);
  const [newDuration, setNewDuration] = useState(60);
  const [newScore, setNewScore] = useState(90);
  const [newSummary, setNewSummary] = useState(
    "Excellent cadence, crisp articulation of value propositions."
  );

  const [mailTo, setMailTo] = useState("");
  const [mailSubject, setMailSubject] = useState(
    "Mindful Orator: Weekly Rehearsal Progress Summary"
  );
  const [mailBody, setMailBody] = useState(
    "Attached is my vocal cadence log and rehearsal feedback report generated by Mindful Orator. Progress towards 145 WPM keynote goal is on track."
  );

  const [feedbackNotice, setFeedbackNotice] = useState<{
    type: "success" | "error";
    message: string;
  } | null>(null);

  // Init Auth
  useEffect(() => {
    initAuth(
      (user, token) => {
        setCurrentUser(user);
        loadWorkspaceData(token);
      },
      () => {
        setCurrentUser(null);
      }
    );
  }, []);

  const handleSignIn = async () => {
    setIsAuthLoading(true);
    setFeedbackNotice(null);
    try {
      const res = await googleSignIn();
      if (res) {
        setCurrentUser(res.user);
        await loadWorkspaceData(res.accessToken);
        setFeedbackNotice({
          type: "success",
          message: "Connected to Google Workspace with Sheets & Gmail permissions.",
        });
      }
    } catch (err: any) {
      console.error("Sign in failed:", err);
      setFeedbackNotice({
        type: "error",
        message: err.message || "Failed to sign in with Google.",
      });
    } finally {
      setIsAuthLoading(false);
    }
  };

  const handleSignOut = async () => {
    await logout();
    setCurrentUser(null);
    setSheetUrl(null);
    setSheetId(null);
    setSheetRows([]);
    setSentEmails([]);
  };

  const loadWorkspaceData = async (token?: string) => {
    const accessToken = token || (await getAccessToken());
    if (!accessToken) return;

    setIsLoadingData(true);
    try {
      // Find or create sheet
      const sheet = await findOrCreateSpreadsheet(accessToken);
      setSheetId(sheet.id);
      setSheetUrl(sheet.url);

      // Fetch rows
      const rows = await fetchRehearsalRows(accessToken, sheet.id);
      setSheetRows(rows);

      // Fetch sent emails
      const emails = await fetchSentRehearsalEmails(accessToken);
      setSentEmails(emails);
    } catch (err) {
      console.error("Failed to load workspace data:", err);
    } finally {
      setIsLoadingData(false);
    }
  };

  // Add Record to Sheets
  const handleConfirmAddRow = async () => {
    setIsProcessing(true);
    try {
      const token = await getAccessToken();
      if (!token || !sheetId) throw new Error("Workspace connection missing");

      const record: RehearsalRecord = {
        timestamp: new Date().toLocaleString(),
        speechTitle: newTitle,
        durationSeconds: newDuration,
        wordCount: Math.round((newWpm / 60) * newDuration),
        wpm: newWpm,
        pacingStatus: newWpm > 160 ? "Fast" : newWpm < 125 ? "Slow" : "Optimal",
        clarityScore: newScore,
        confidenceScore: Math.min(100, newScore + 2),
        fillerWordsTotal: 1,
        overallTone: "Commanding & Articulate",
        executiveSummary: newSummary,
      };

      await appendRehearsalRow(token, sheetId, record);
      await loadWorkspaceData(token);

      setAddSheetModalOpen(false);
      setFeedbackNotice({
        type: "success",
        message: `Appended practice session "${newTitle}" to Google Sheets.`,
      });
    } catch (err: any) {
      setFeedbackNotice({
        type: "error",
        message: err.message || "Failed to add row to Google Sheets.",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  // Send Email via Gmail
  const handleConfirmSendEmail = async () => {
    if (!mailTo.trim()) {
      alert("Please specify a recipient email address.");
      return;
    }
    setIsProcessing(true);
    try {
      const token = await getAccessToken();
      if (!token) throw new Error("Workspace connection missing");

      const bodyHtml = `
        <div style="font-family: sans-serif; line-height: 1.6; color: #1e293b;">
          <h2 style="color: #3525cd;">Mindful Orator Practice Report</h2>
          <p>${mailBody}</p>
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 16px 0;" />
          <p style="font-size: 13px; color: #64748b;">
            Logged via Mindful Orator AI Speech Coach with Google Sheets sync.
          </p>
        </div>
      `;

      await sendRehearsalEmail(token, {
        to: mailTo,
        subject: mailSubject,
        bodyHtml,
      });

      await loadWorkspaceData(token);
      setSendMailModalOpen(false);
      setFeedbackNotice({
        type: "success",
        message: `Email sent to ${mailTo} via Gmail.`,
      });
    } catch (err: any) {
      setFeedbackNotice({
        type: "error",
        message: err.message || "Failed to send email via Gmail.",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200/80 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-800 border border-emerald-200">
                <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-700" />
                Google Workspace Integration
              </span>
            </div>
            <h2 className="text-2xl font-bold tracking-tight text-[#131b2e] mt-2">
              Google Sheets Rehearsal Log & Gmail Dispatcher
            </h2>
            <p className="text-sm text-[#464555] mt-1 max-w-2xl leading-relaxed">
              Maintain an enduring rehearsal ledger in Google Sheets and dispatch feedback reports or vocal notes to yourself and mentors via Gmail with end-user permissions.
            </p>
          </div>

          <div>
            {!currentUser ? (
              <GoogleSignInButton
                onClick={handleSignIn}
                isLoading={isAuthLoading}
                label="Connect Google Workspace"
              />
            ) : (
              <div className="flex items-center gap-3">
                <div className="flex items-center gap-2 px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-700">
                  <User className="w-3.5 h-3.5 text-[#3525cd]" />
                  <span>{currentUser.email || "Connected"}</span>
                </div>
                <button
                  onClick={handleSignOut}
                  className="p-2 text-slate-400 hover:text-slate-700 bg-slate-50 hover:bg-slate-100 rounded-xl border border-slate-200 transition-colors cursor-pointer"
                  title="Sign out"
                >
                  <LogOut className="w-4 h-4" />
                </button>
              </div>
            )}
          </div>
        </div>

        {feedbackNotice && (
          <div
            className={`mt-4 p-3.5 rounded-xl border text-xs flex items-start gap-2.5 ${
              feedbackNotice.type === "success"
                ? "bg-emerald-50 border-emerald-200 text-emerald-800"
                : "bg-rose-50 border-rose-200 text-rose-800"
            }`}
          >
            {feedbackNotice.type === "success" ? (
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
            ) : (
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
            )}
            <div>
              <p className="font-semibold">
                {feedbackNotice.type === "success" ? "Success" : "Error"}
              </p>
              <p className="mt-0.5">{feedbackNotice.message}</p>
            </div>
          </div>
        )}
      </div>

      {!currentUser ? (
        <div className="bg-white rounded-2xl p-12 border border-slate-200/80 shadow-xs text-center max-w-xl mx-auto space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-[#3525cd] mx-auto">
            <Table className="w-6 h-6" />
          </div>
          <h3 className="text-lg font-bold text-[#131b2e]">
            Connect Google Sheets & Gmail
          </h3>
          <p className="text-sm text-[#464555] leading-relaxed">
            Authorize Mindful Orator to sync practice recordings, cadence curves (WPM), and filler word metrics into your personal Google Sheets, and send rehearsal summaries via Gmail.
          </p>
          <div className="pt-2">
            <GoogleSignInButton
              onClick={handleSignIn}
              isLoading={isAuthLoading}
              label="Sign in with Google"
            />
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left: Google Sheets Live Ledger */}
          <div className="lg:col-span-7 bg-white rounded-2xl p-6 border border-slate-200/80 shadow-xs flex flex-col justify-between space-y-4">
            <div>
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-100">
                <div className="flex items-center gap-2">
                  <Table className="w-4 h-4 text-emerald-600" />
                  <h3 className="text-sm font-bold uppercase tracking-wider text-[#464555]">
                    Google Sheets Practice Log
                  </h3>
                </div>

                <div className="flex items-center gap-2">
                  {sheetUrl && (
                    <a
                      href={sheetUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="px-2.5 py-1 text-xs font-medium text-emerald-700 bg-emerald-50 hover:bg-emerald-100 rounded-lg border border-emerald-200 flex items-center gap-1 transition-colors"
                    >
                      <span>Open in Sheets</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  )}

                  <button
                    onClick={() => loadWorkspaceData()}
                    disabled={isLoadingData}
                    className="p-1 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer"
                    title="Refresh data"
                  >
                    <RefreshCw className={`w-3.5 h-3.5 ${isLoadingData ? "animate-spin" : ""}`} />
                  </button>

                  <button
                    onClick={() => setAddSheetModalOpen(true)}
                    className="px-2.5 py-1 text-xs font-semibold text-white bg-[#3525cd] hover:bg-[#4f46e5] rounded-lg shadow-2xs flex items-center gap-1 transition-all cursor-pointer"
                  >
                    <Plus className="w-3 h-3" />
                    <span>Log Rehearsal</span>
                  </button>
                </div>
              </div>

              {/* Table Preview */}
              <div className="mt-4 overflow-x-auto">
                {sheetRows.length > 0 ? (
                  <table className="w-full text-left text-xs border-collapse">
                    <thead>
                      <tr className="bg-slate-50 border-b border-slate-200 text-slate-600 font-semibold">
                        {sheetRows[0].slice(0, 5).map((col, idx) => (
                          <th key={idx} className="p-2.5 whitespace-nowrap">
                            {col}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 text-slate-700">
                      {sheetRows.slice(1).map((row, rIdx) => (
                        <tr key={rIdx} className="hover:bg-slate-50/70 transition-colors">
                          <td className="p-2.5 whitespace-nowrap text-slate-500 font-mono text-[11px]">
                            {row[0] || "--"}
                          </td>
                          <td className="p-2.5 font-medium text-[#131b2e]">{row[1] || "--"}</td>
                          <td className="p-2.5 font-mono">{row[2] || "--"}s</td>
                          <td className="p-2.5 font-mono">{row[3] || "--"}</td>
                          <td className="p-2.5 font-mono font-semibold text-[#3525cd]">
                            {row[4] || "--"}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                ) : (
                  <div className="py-12 text-center text-slate-400 text-xs">
                    {isLoadingData ? (
                      <p>Loading spreadsheet records from Google Drive...</p>
                    ) : (
                      <p>No rehearsal entries yet. Click "Log Rehearsal" to append your first session.</p>
                    )}
                  </div>
                )}
              </div>
            </div>

            <p className="text-[11px] text-slate-400 pt-2 border-t border-slate-100">
              Connected Spreadsheet: <strong>Mindful Orator - Speech Practice Log</strong>
            </p>
          </div>

          {/* Right: Gmail Dispatcher */}
          <div className="lg:col-span-5 bg-white rounded-2xl p-6 border border-slate-200/80 shadow-xs flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center justify-between pb-3 border-b border-slate-100">
                <div className="flex items-center gap-2">
                  <Mail className="w-4 h-4 text-[#3525cd]" />
                  <h3 className="text-sm font-bold uppercase tracking-wider text-[#464555]">
                    Gmail Dispatcher
                  </h3>
                </div>

                <button
                  onClick={() => setSendMailModalOpen(true)}
                  className="px-2.5 py-1 text-xs font-semibold text-white bg-[#3525cd] hover:bg-[#4f46e5] rounded-lg shadow-2xs flex items-center gap-1 transition-all cursor-pointer"
                >
                  <Send className="w-3 h-3" />
                  <span>Send Report</span>
                </button>
              </div>

              {/* Sent history list */}
              <div className="mt-4 space-y-2.5">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  Recent Dispatches via Gmail
                </h4>
                {sentEmails.length > 0 ? (
                  sentEmails.map((em) => (
                    <div
                      key={em.id}
                      className="p-3 bg-slate-50 rounded-xl border border-slate-100 text-xs space-y-1"
                    >
                      <div className="flex items-center justify-between text-slate-500 font-mono text-[10px]">
                        <span>{em.date || "Recently sent"}</span>
                        <span className="text-emerald-700 font-medium">Sent</span>
                      </div>
                      <p className="font-semibold text-[#131b2e] line-clamp-1">{em.subject}</p>
                      <p className="text-slate-500 line-clamp-2">{em.snippet}</p>
                    </div>
                  ))
                ) : (
                  <div className="py-8 text-center text-slate-400 text-xs">
                    <p>No reports dispatched yet.</p>
                    <p className="mt-1">
                      Click "Send Report" to email yourself or a mentor your speech analysis.
                    </p>
                  </div>
                )}
              </div>
            </div>

            <div className="p-3 bg-indigo-50/50 rounded-xl border border-indigo-100/70 text-xs text-[#3525cd]">
              <p className="font-semibold">Gmail Integration Note</p>
              <p className="text-[11px] text-slate-600 mt-0.5">
                Emails are sent directly from your authentic Google account via Gmail API. Every mutation requests explicit confirmation.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Confirmation Modal: Add to Sheets */}
      <ConfirmModal
        isOpen={addSheetModalOpen}
        title="Append Practice Record to Google Sheets"
        description="Are you sure you want to write this rehearsal entry to your spreadsheet? This action will append a new row to 'Mindful Orator - Speech Practice Log'."
        confirmLabel="Confirm & Append Row"
        cancelLabel="Cancel"
        isProcessing={isProcessing}
        details={[
          `Speech: ${newTitle}`,
          `Duration: ${newDuration}s | Cadence: ${newWpm} WPM`,
          `Score: ${newScore}/100`,
        ]}
        onConfirm={handleConfirmAddRow}
        onCancel={() => setAddSheetModalOpen(false)}
      >
        <div className="space-y-3 mt-3">
          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">
              Speech Title
            </label>
            <input
              type="text"
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
            />
          </div>
          <div className="grid grid-cols-3 gap-2">
            <div>
              <label className="block text-xs font-medium text-slate-600 mb-1">
                WPM
              </label>
              <input
                type="number"
                value={newWpm}
                onChange={(e) => setNewWpm(Number(e.target.value))}
                className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-600 mb-1">
                Duration (s)
              </label>
              <input
                type="number"
                value={newDuration}
                onChange={(e) => setNewDuration(Number(e.target.value))}
                className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-600 mb-1">
                Score (100)
              </label>
              <input
                type="number"
                value={newScore}
                onChange={(e) => setNewScore(Number(e.target.value))}
                className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
              />
            </div>
          </div>
          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">
              Feedback Summary
            </label>
            <textarea
              rows={2}
              value={newSummary}
              onChange={(e) => setNewSummary(e.target.value)}
              className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
            />
          </div>
        </div>
      </ConfirmModal>

      {/* Confirmation Modal: Send Email via Gmail */}
      <ConfirmModal
        isOpen={sendMailModalOpen}
        title="Send Rehearsal Summary via Gmail"
        description="Are you sure you want to dispatch this email from your connected Gmail address? This will send an email through the Gmail API."
        confirmLabel="Confirm & Send via Gmail"
        cancelLabel="Cancel"
        isProcessing={isProcessing}
        details={[`Subject: ${mailSubject}`, `To: ${mailTo || "(enter below)"}`]}
        onConfirm={handleConfirmSendEmail}
        onCancel={() => setSendMailModalOpen(false)}
      >
        <div className="space-y-3 mt-3">
          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">
              Recipient Email Address (required)
            </label>
            <input
              type="email"
              value={mailTo}
              onChange={(e) => setMailTo(e.target.value)}
              placeholder="coach@example.com or your email"
              className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">
              Subject
            </label>
            <input
              type="text"
              value={mailSubject}
              onChange={(e) => setMailSubject(e.target.value)}
              className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-slate-600 mb-1">
              Message Body
            </label>
            <textarea
              rows={3}
              value={mailBody}
              onChange={(e) => setMailBody(e.target.value)}
              className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none"
            />
          </div>
        </div>
      </ConfirmModal>
    </div>
  );
};
